- name: create kube-apiserver.service systemd unit
  template: src=kube-apiserver.service.j2 dest=/etc/systemd/system/kube-apiserver.service
  notify: restart_apiserver

- name: create kube-scheduler.service systemd unit
  template: src=kube-scheduler.service.j2 dest=/etc/systemd/system/kube-scheduler.service
  notify: restart_scheduler
  
- name: create kube-controller-manager.service systemd unit
  template: src=kube-controller-manager.service.j2 dest=/etc/systemd/system/kube-controller-manager.service
  notify: restart_controller_manager
  
- meta: flush_handlers

- name: create manifests for apiserver->kubelet authorization 
  copy: src={{ item }}  dest=/etc/kubernetes/{{ item }}
  with_items:
  - apiserver-to-kubelet-cr.yaml
  - apiserver-to-kubelet-rb.yaml
  notify: apply_api_kubelet_auth
