- name: apply_calico_rbac
  shell: kubectl apply -f /etc/kubernetes/calico-rbac.yaml
  register: result
  until: result.rc == 0
  retries: 24
  delay: 5
  delegate_to: "{{ groups.k8s_masters[0] }}"
  run_once: true

- name: apply_calico_deploy
  shell: kubectl apply -f /etc/kubernetes/calico-cni.yaml
  delegate_to: "{{ groups.k8s_masters[0] }}"
  run_once: true

- name: apply_kubedns_deploy
  shell: kubectl apply -f /etc/kubernetes/kube-dns.yaml
  delegate_to: "{{ groups.k8s_masters[0] }}"
  run_once: true
