- name: apply_calico_rbac
  shell: |
    TIMEOUT=0
    until kubectl apply -f /etc/kubernetes/calico-rbac.yaml; do
      if [[ "$TIMEOUT" -lt "180" ]]; then
        sleep 2
        TIMEOUT=$(($TIMEOUT+2))
      else
        exit 1
      fi
    done
  delegate_to: "{{ groups.k8s_masters[0] }}"
  run_once: true

- name: apply_calico_deploy
  shell: kubectl apply -f /etc/kubernetes/calico-cni.yaml
  delegate_to: "{{ groups.k8s_masters[0] }}"
  run_once: true

- name: apply_kubedns_deploy
  shell: kubectl apply -f /etc/kubernetes/kube-dns.yaml
  delegate_to: "{{ groups.k8s_masters[0] }}"
  run_once: true
