- name: restart_apiserver
  systemd: name=kube-apiserver state=restarted enabled=yes daemon_reload=yes

- name: restart_scheduler
  systemd: name=kube-scheduler state=restarted enabled=yes daemon_reload=yes

- name: restart_controller_manager
  systemd: name=kube-controller-manager state=restarted enabled=yes daemon_reload=yes

- name: apply_api_kubelet_auth
  shell: kubectl apply -f /etc/kubernetes/{{ item }}
  with_items:
  - apiserver-to-kubelet-cr.yaml
  - apiserver-to-kubelet-rb.yaml
  register: result
  until: result.rc == 0
  retries: 24
  delay: 5
  delegate_to: "{{ groups.k8s_masters[0] }}"
  run_once: true
